### ISSUE TITLE
Infogreffe ?

### ISSUE THREAD

**Issue by yongicobay** [pcotret/ctf-writeups#1]
Bonjour,

ayant galéré sur l"épreuve la belle porte,  que j'ai résolue d'une manière très détournée, j'aimerais par acquit de conscience comprendre ce que j'ai raté : j'ai moi aussi pensé à infogreffe, mais n'y ai rien trouvé concernant le trou à brest. De plus l'URL que vous indiquez renvoie vers une page indiquant (comme moi) aucun résultat. Avez vous un abonnement payant ? y a-t-il des options de rercherche qui ne figure pas dans l'URL ? le résultat n'existerait il plus ?!?

En vous remerciant pour ces excellents write up, qui me permettent de progresser

**Comment by pcotret** [comment]
Oups, l'URL n'est pas permanente en effet...
https://www.infogreffe.fr/ et "le trou brest" dans le champ de recherche et j'ai bien un seul résultat chez moi :/
![image](https://user-images.githubusercontent.com/404135/99154681-ef40cb80-26b1-11eb-961e-f9f481c64e57.png)
